module.exports = {
  FORUM_USER: 'FORUM_USER',
  FORUM_CATEGORY: 'FORUM_CATEGORY',
  FORUM_THREAD: 'FORUM_THREAD',
  FORUM_POST: 'FORUM_POST',
  FORUM_VOTE: 'FORUM_VOTE',
  FORUM_ROLE: 'FORUM_ROLE',
  FORUM_MODERATION: 'FORUM_MODERATION',
  FORUM_INDEX: 'FORUM_INDEX',
  FORUM_CONFIG: 'FORUM_CONFIG',
};
