module.exports = {
  FORUM_USER: 'FORUM_USER',
  FORUM_CATEGORY: 'FORUM_CATEGORY',
  FORUM_THREAD: 'FORUM_THREAD',
  FORUM_POST: 'FORUM_POST',
  FORUM_VOTE: 'FORUM_VOTE',
  FORUM_ROLE: 'FORUM_ROLE',
  FORUM_MODERATION: 'FORUM_MODERATION',
  FORUM_INDEX: 'FORUM_INDEX',
  FORUM_CONFIG: 'FORUM_CONFIG',

  // --- Payment & marketplace tags (new) ---
  FORUM_TIP: 'FORUM_TIP',
  FORUM_SUBSCRIPTION: 'FORUM_SUBSCRIPTION',
  FORUM_PURCHASE: 'FORUM_PURCHASE',
  FORUM_BADGE: 'FORUM_BADGE',
  FORUM_ESCROW_CREATED: 'FORUM_ESCROW_CREATED',
  FORUM_ESCROW_UPDATED: 'FORUM_ESCROW_UPDATED',
  FORUM_RATING: 'FORUM_RATING',
};
