[package]
name = "IotaFreeForum"
version = "0.1.0"
edition = "2024"

[dependencies]
Iota = { local = "../../.tmp/iota-framework/crates/iota-framework/packages/iota-framework" }

[addresses]
forum = "0x0"
